# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [1]:
import numpy as np
np.set_printoptions(precision=2)

### What version of NumPy are you using?

In [2]:
np.__version__

'1.20.3'

### Display array elements in reverse order

In [3]:
array1 = np.arange(3)

In [4]:
np.flip(array1)

array([2, 1, 0])

### Triple elements in array

In [5]:
print('first option:', np.tile(array1,3))
print('second option:', np.tile(array1,(3,1)))

first option: [0 1 2 0 1 2 0 1 2]
second option: [[0 1 2]
 [0 1 2]
 [0 1 2]]


### Create array with 20 zeros; every fifth element equals four

In [6]:
array2 = np.zeros(20)
array2[4::5] = 4
array2

array([0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0.,
       0., 0., 4.])

### Create a 5x5 identity matrix with integer components

In [7]:
matrix1 = np.eye(5,dtype='int32')
matrix1[0,1] = 999
matrix1

array([[  1, 999,   0,   0,   0],
       [  0,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0],
       [  0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   1]])

### Transpose the rows and columns

In [8]:
matrix1.T

array([[  1,   0,   0,   0,   0],
       [999,   1,   0,   0,   0],
       [  0,   0,   1,   0,   0],
       [  0,   0,   0,   1,   0],
       [  0,   0,   0,   0,   1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [9]:
vector1 = np.random.random(30)
print(vector1)
print(vector1.mean())

[0.33 0.54 0.91 0.03 0.32 0.02 0.6  0.22 0.73 0.8  0.31 0.45 0.8  0.53
 0.73 0.33 0.5  0.81 0.75 0.04 0.91 0.41 0.1  0.49 0.01 0.68 0.65 0.11
 0.86 0.37]
0.47817177605108063


### Create an 8x8 checker board with alternating zeros and ones

In [10]:
checker_board = np.zeros(8*8).reshape(8,8)
checker_board[1::2,::2] = 1
checker_board[0::2,1::2] = 1
checker_board

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [11]:
def sorter(n):
    output = np.arange(n)
    output = np.sort(output)
    return output
sorter(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Create a sorted vector that contain 'n' random numbers

In [12]:
import numpy as np
def sorted_vector(n):
    output = np.random.random(n)
    return np.sort(output)
sorted_vector(10)

array([0.13, 0.21, 0.29, 0.41, 0.43, 0.53, 0.63, 0.65, 0.66, 0.82])

### Without sorting, replace largest element in random array with the value 1234

In [13]:
array3 = np.random.random(8)
array3[array3.argmax()] = 1234
np.set_printoptions(precision=2,suppress=True)
array3_list = list(np.around(array3,2))
print(array3_list)
print(np.array(array3_list))


[1234.0, 0.55, 0.6, 0.43, 0.32, 0.88, 0.02, 0.12]
[1234.      0.55    0.6     0.43    0.32    0.88    0.02    0.12]


### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [14]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [15]:
structured_camelot_values = np.array(camelot_values,dtype=camelot_dtype)
sorted_camelot_values = np.sort(structured_camelot_values, order='height')
print(sorted_camelot_values)
for i in sorted_camelot_values:
    print(i)
#np.sort(a, order='height')

[(b'Galahad', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]
(b'Galahad', 1.7, 38)
(b'Arthur', 1.8, 41)
(b'Lancelot', 1.9, 38)


### Make an array read-only (immutable)

In [16]:
array4 = np.arange(10)
array4.setflags(write=False)

### Print enumerated values from a 3x3 NumPy array

In [17]:
array5 = np.arange(9).reshape(3,3) + 1
print(array5)
print(np.ndenumerate(array5))
for (index, value) in np.ndenumerate(array5):
    print (index, value)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9
